# Created by and for Qt Creator. This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = featureTracking

HEADERS = \
   $$PWD/build/git/googletest/googlemock/include/gmock/internal/custom/gmock-generated-actions.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/internal/custom/gmock-matchers.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/internal/custom/gmock-port.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/internal/gmock-port.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/gmock-actions.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/gmock-cardinalities.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/gmock-generated-actions.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/gmock-generated-matchers.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/gmock-generated-nice-strict.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/gmock-matchers.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/gmock-more-actions.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/gmock-more-matchers.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/gmock-spec-builders.h \
   $$PWD/build/git/googletest/googlemock/include/gmock/gmock.h \
   $$PWD/build/git/googletest/googlemock/test/gmock_link_test.h \
   $$PWD/build/git/googletest/googletest/include/gtest/internal/custom/gtest-port.h \
   $$PWD/build/git/googletest/googletest/include/gtest/internal/custom/gtest-printers.h \
   $$PWD/build/git/googletest/googletest/include/gtest/internal/custom/gtest.h \
   $$PWD/build/git/googletest/googletest/include/gtest/internal/gtest-death-test-internal.h \
   $$PWD/build/git/googletest/googletest/include/gtest/internal/gtest-filepath.h \
   $$PWD/build/git/googletest/googletest/include/gtest/internal/gtest-internal.h \
   $$PWD/build/git/googletest/googletest/include/gtest/internal/gtest-linked_ptr.h \
   $$PWD/build/git/googletest/googletest/include/gtest/internal/gtest-param-util-generated.h \
   $$PWD/build/git/googletest/googletest/include/gtest/internal/gtest-param-util.h \
   $$PWD/build/git/googletest/googletest/include/gtest/internal/gtest-port-arch.h \
   $$PWD/build/git/googletest/googletest/include/gtest/internal/gtest-port.h \
   $$PWD/build/git/googletest/googletest/include/gtest/internal/gtest-string.h \
   $$PWD/build/git/googletest/googletest/include/gtest/internal/gtest-tuple.h \
   $$PWD/build/git/googletest/googletest/include/gtest/internal/gtest-type-util.h \
   $$PWD/build/git/googletest/googletest/include/gtest/gtest-death-test.h \
   $$PWD/build/git/googletest/googletest/include/gtest/gtest-message.h \
   $$PWD/build/git/googletest/googletest/include/gtest/gtest-param-test.h \
   $$PWD/build/git/googletest/googletest/include/gtest/gtest-printers.h \
   $$PWD/build/git/googletest/googletest/include/gtest/gtest-spi.h \
   $$PWD/build/git/googletest/googletest/include/gtest/gtest-test-part.h \
   $$PWD/build/git/googletest/googletest/include/gtest/gtest-typed-test.h \
   $$PWD/build/git/googletest/googletest/include/gtest/gtest.h \
   $$PWD/build/git/googletest/googletest/include/gtest/gtest_pred_impl.h \
   $$PWD/build/git/googletest/googletest/include/gtest/gtest_prod.h \
   $$PWD/build/git/googletest/googletest/samples/prime_tables.h \
   $$PWD/build/git/googletest/googletest/samples/sample1.h \
   $$PWD/build/git/googletest/googletest/samples/sample2.h \
   $$PWD/build/git/googletest/googletest/samples/sample3-inl.h \
   $$PWD/build/git/googletest/googletest/samples/sample4.h \
   $$PWD/build/git/googletest/googletest/src/gtest-internal-inl.h \
   $$PWD/build/git/googletest/googletest/test/gtest-param-test_test.h \
   $$PWD/build/git/googletest/googletest/test/gtest-typed-test_test.h \
   $$PWD/build/git/googletest/googletest/test/production.h \
   $$PWD/build/git/googletest/googletest/xcode/Samples/FrameworkSample/widget.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/internal/custom/gmock-generated-actions.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/internal/custom/gmock-matchers.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/internal/custom/gmock-port.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/internal/gmock-port.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/gmock-actions.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/gmock-cardinalities.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/gmock-generated-actions.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/gmock-generated-matchers.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/gmock-generated-nice-strict.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/gmock-matchers.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/gmock-more-actions.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/gmock-more-matchers.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/gmock-spec-builders.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/gmock.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock_link_test.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/custom/gtest-port.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/custom/gtest-printers.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/custom/gtest.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/gtest-death-test-internal.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/gtest-filepath.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/gtest-internal.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/gtest-linked_ptr.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/gtest-param-util-generated.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/gtest-param-util.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/gtest-port-arch.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/gtest-port.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/gtest-string.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/gtest-tuple.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/gtest-type-util.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/gtest-death-test.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/gtest-message.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/gtest-param-test.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/gtest-printers.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/gtest-spi.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/gtest-test-part.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/gtest-typed-test.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/gtest.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/gtest_pred_impl.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/gtest_prod.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/prime_tables.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample1.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample2.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample3-inl.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample4.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/src/gtest-internal-inl.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-param-test_test.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-typed-test_test.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/production.h \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/xcode/Samples/FrameworkSample/widget.h \
   $$PWD/include/detectors/AdaptativeThresholdDetect.hpp \
   $$PWD/include/detectors/CannyDetect.hpp \
   $$PWD/include/detectors/FastDetect.hpp \
   $$PWD/include/detectors/FeatureDetect.hpp \
   $$PWD/include/detectors/FindContourDetect.hpp \
   $$PWD/include/detectors/HarrisCornerDetect.hpp \
   $$PWD/include/detectors/HarrisLaplaceDetect.hpp \
   $$PWD/include/detectors/HoughDetect.hpp \
   $$PWD/include/detectors/KMeanDetect.hpp \
   $$PWD/include/detectors/LucidDetect.hpp \
   $$PWD/include/detectors/MSDDetectorDetect.hpp \
   $$PWD/include/detectors/OtsuThresholdDetect.hpp \
   $$PWD/include/detectors/RoadDetect.hpp \
   $$PWD/include/detectors/SegmentationDetect.hpp \
   $$PWD/include/detectors/SiftDetect.hpp \
   $$PWD/include/detectors/SimpleBlobDetect.hpp \
   $$PWD/include/detectors/StarDetectorDetect.hpp \
   $$PWD/include/detectors/SurfDetect.hpp \
   $$PWD/include/detectors/ThresholdDetect.hpp \
   $$PWD/include/detectors/VggDetect.hpp \
   $$PWD/include/trackers/Tracker.hpp \
   $$PWD/include/util/Debug.hpp \
   $$PWD/include/util/GridMosaic.hpp \
   $$PWD/include/util/Mosaic.hpp \
   $$PWD/include/util/Stats.hpp \
   $$PWD/include/util/Timing.hpp

SOURCES = \
   $$PWD/build/CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c \
   $$PWD/build/CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp \
   $$PWD/build/CMakeFiles/feature_tests.c \
   $$PWD/build/CMakeFiles/feature_tests.cxx \
   $$PWD/build/git/googletest/googlemock/src/gmock-all.cc \
   $$PWD/build/git/googletest/googlemock/src/gmock-cardinalities.cc \
   $$PWD/build/git/googletest/googlemock/src/gmock-internal-utils.cc \
   $$PWD/build/git/googletest/googlemock/src/gmock-matchers.cc \
   $$PWD/build/git/googletest/googlemock/src/gmock-spec-builders.cc \
   $$PWD/build/git/googletest/googlemock/src/gmock.cc \
   $$PWD/build/git/googletest/googlemock/src/gmock_main.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock-actions_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock-cardinalities_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock-generated-actions_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock-generated-function-mockers_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock-generated-internal-utils_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock-generated-matchers_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock-internal-utils_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock-matchers_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock-more-actions_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock-nice-strict_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock-port_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock-spec-builders_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock_all_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock_ex_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock_leak_test_.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock_link2_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock_link_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock_output_test_.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock_stress_test.cc \
   $$PWD/build/git/googletest/googlemock/test/gmock_test.cc \
   $$PWD/build/git/googletest/googletest/codegear/gtest_all.cc \
   $$PWD/build/git/googletest/googletest/codegear/gtest_link.cc \
   $$PWD/build/git/googletest/googletest/samples/sample1.cc \
   $$PWD/build/git/googletest/googletest/samples/sample10_unittest.cc \
   $$PWD/build/git/googletest/googletest/samples/sample1_unittest.cc \
   $$PWD/build/git/googletest/googletest/samples/sample2.cc \
   $$PWD/build/git/googletest/googletest/samples/sample2_unittest.cc \
   $$PWD/build/git/googletest/googletest/samples/sample3_unittest.cc \
   $$PWD/build/git/googletest/googletest/samples/sample4.cc \
   $$PWD/build/git/googletest/googletest/samples/sample4_unittest.cc \
   $$PWD/build/git/googletest/googletest/samples/sample5_unittest.cc \
   $$PWD/build/git/googletest/googletest/samples/sample6_unittest.cc \
   $$PWD/build/git/googletest/googletest/samples/sample7_unittest.cc \
   $$PWD/build/git/googletest/googletest/samples/sample8_unittest.cc \
   $$PWD/build/git/googletest/googletest/samples/sample9_unittest.cc \
   $$PWD/build/git/googletest/googletest/src/gtest-all.cc \
   $$PWD/build/git/googletest/googletest/src/gtest-death-test.cc \
   $$PWD/build/git/googletest/googletest/src/gtest-filepath.cc \
   $$PWD/build/git/googletest/googletest/src/gtest-port.cc \
   $$PWD/build/git/googletest/googletest/src/gtest-printers.cc \
   $$PWD/build/git/googletest/googletest/src/gtest-test-part.cc \
   $$PWD/build/git/googletest/googletest/src/gtest-typed-test.cc \
   $$PWD/build/git/googletest/googletest/src/gtest.cc \
   $$PWD/build/git/googletest/googletest/src/gtest_main.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-death-test_ex_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-death-test_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-filepath_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-linked_ptr_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-listener_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-message_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-options_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-param-test2_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-param-test_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-port_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-printers_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-test-part_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-tuple_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-typed-test2_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-typed-test_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest-unittest-api_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_all_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_break_on_failure_unittest_.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_catch_exceptions_test_.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_color_test_.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_env_var_test_.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_environment_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_filter_unittest_.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_help_test_.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_list_tests_unittest_.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_main_unittest.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_no_test_unittest.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_output_test_.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_pred_impl_unittest.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_premature_exit_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_prod_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_repeat_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_shuffle_test_.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_sole_header_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_stress_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_throw_on_failure_ex_test.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_throw_on_failure_test_.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_uninitialized_test_.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_unittest.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_xml_outfile1_test_.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_xml_outfile2_test_.cc \
   $$PWD/build/git/googletest/googletest/test/gtest_xml_output_unittest_.cc \
   $$PWD/build/git/googletest/googletest/test/production.cc \
   $$PWD/build/git/googletest/googletest/xcode/Samples/FrameworkSample/widget.cc \
   $$PWD/build/git/googletest/googletest/xcode/Samples/FrameworkSample/widget_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/src/gmock-all.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/src/gmock-cardinalities.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/src/gmock-internal-utils.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/src/gmock-matchers.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/src/gmock-spec-builders.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/src/gmock.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/src/gmock_main.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock-actions_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock-cardinalities_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock-generated-actions_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock-generated-function-mockers_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock-generated-internal-utils_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock-generated-matchers_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock-internal-utils_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock-matchers_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock-more-actions_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock-nice-strict_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock-port_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock-spec-builders_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock_all_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock_ex_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock_leak_test_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock_link2_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock_link_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock_output_test_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock_stress_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test/gmock_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/codegear/gtest_all.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/codegear/gtest_link.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample1.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample10_unittest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample1_unittest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample2.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample2_unittest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample3_unittest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample4.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample4_unittest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample5_unittest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample6_unittest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample7_unittest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample8_unittest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples/sample9_unittest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/src/gtest-all.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/src/gtest-death-test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/src/gtest-filepath.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/src/gtest-port.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/src/gtest-printers.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/src/gtest-test-part.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/src/gtest-typed-test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/src/gtest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/src/gtest_main.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-death-test_ex_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-death-test_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-filepath_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-linked_ptr_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-listener_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-message_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-options_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-param-test2_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-param-test_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-port_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-printers_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-test-part_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-tuple_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-typed-test2_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-typed-test_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest-unittest-api_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_all_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_break_on_failure_unittest_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_catch_exceptions_test_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_color_test_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_env_var_test_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_environment_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_filter_unittest_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_help_test_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_list_tests_unittest_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_main_unittest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_no_test_unittest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_output_test_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_pred_impl_unittest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_premature_exit_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_prod_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_repeat_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_shuffle_test_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_sole_header_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_stress_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_throw_on_failure_ex_test.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_throw_on_failure_test_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_uninitialized_test_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_unittest.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_xml_outfile1_test_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_xml_outfile2_test_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/gtest_xml_output_unittest_.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test/production.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/xcode/Samples/FrameworkSample/widget.cc \
   $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/xcode/Samples/FrameworkSample/widget_test.cc \
   $$PWD/src/detectors/FeatureDetect.cpp \
   $$PWD/src/trackers/Tracker.cpp \
   $$PWD/src/util/Debug.cpp \
   $$PWD/src/util/GridMosaic.cpp \
   $$PWD/src/util/Mosaic.cpp \
   $$PWD/src/featureDetectorDemo.cpp \
   $$PWD/src/Mosaic.cpp \
   $$PWD/src/Mosaic0.cpp \
   $$PWD/src/surfMatchDemo.cpp \
   $$PWD/test/src/test/dummy2_ut.cpp \
   $$PWD/test/src/dummy_ut.cpp \
   $$PWD/test/src/main.cpp \
   $$PWD/tools/cmake/git.cmake \
   $$PWD/tools/cmake/gitCMakeLists.txt \
   $$PWD/tools/cmake/versions.cmake \
   $$PWD/CMakeLists.txt \
   $$PWD/LICENSE \
   $$PWD/README.md

INCLUDEPATH = \
    $$PWD/build/git/googletest/googlemock/include/gmock \
    $$PWD/build/git/googletest/googlemock/include/gmock/internal \
    $$PWD/build/git/googletest/googlemock/include/gmock/internal/custom \
    $$PWD/build/git/googletest/googlemock/test \
    $$PWD/build/git/googletest/googletest/include/gtest \
    $$PWD/build/git/googletest/googletest/include/gtest/internal \
    $$PWD/build/git/googletest/googletest/include/gtest/internal/custom \
    $$PWD/build/git/googletest/googletest/samples \
    $$PWD/build/git/googletest/googletest/src \
    $$PWD/build/git/googletest/googletest/test \
    $$PWD/build/git/googletest/googletest/xcode/Samples/FrameworkSample \
    $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock \
    $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/internal \
    $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/include/gmock/internal/custom \
    $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googlemock/test \
    $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest \
    $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal \
    $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/include/gtest/internal/custom \
    $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/samples \
    $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/src \
    $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/test \
    $$PWD/build/tmp/googletest/googletest-prefix/src/googletest/googletest/xcode/Samples/FrameworkSample

#DEFINES = 

